// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare global {
  const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
  const MAIN_WINDOW_VITE_NAME: string;

  interface Window {
    electron: {
      onGoogleAuthCode: (callback: (code: string) => void) => () => void;
      changeLanguage: (lang: string) => void;
    };
  }
}

export {};
